project_id = "royuzcroobvazlpjkrql"

[functions.send-to-bitrix]
verify_jwt = false

[functions.submit-to-sheets]
verify_jwt = false

[functions.update-sheet-status]
verify_jwt = false

[functions.sync-from-sheets]
verify_jwt = false